### ISSUE TITLE
Reports do not show up

### ISSUE THREAD

**Issue by antapos** [axelor/abs-webapp#1]
No BIRT report can be shown in the UI of abs-webapp.

Steps to reproduce:
* follow the instructions in the README to checkout main project and git submodules
* setup the postgres database using the db properties shown in abs-webapp/src/main/resources/application.properties
* run the web app using ./gradlew tomcatRun
* open a chrome web browser and open the devtools and the network tab
* login using admin/admin and visit the URL: http://localhost:8080/abs-webapp/#/ds/hr.root.employee/edit/13
* press the 'Print CV' button
* in the network tab of Chrome devtools it shows an error like the following:

HTTP 404 while trying to perform HTTP GET on URL:
http://localhost:8080/birt/frameset?__report=report/Employee.rptdesign&DBName=jdbc:postgresql://localhost:5432/axelor-business-suite&UserName=axelor&Password=*****&__format=pdf&Locale=en&EmployeeId=13

**Comment by marioestradarosa** [comment]
First , I installed a tomcat 7.x . then ran ``` ./gradlew war ```  from your project. copied the abs-webappxxx.war to my ``` /opt/tomcat7/webapps/abs-webapp.war ``` . then downloaded the birt-4.4.2 runtime engine. After unzipping it, I copied the birt.war into ```/opt/tomcat7/webapps ``` also. I also copied the jdbc driver from postgresql to ```/opt/tomcat7/lib```  .  

And then, here is the funny part, I was playing with 
``` http://localhost:8080/abs-webapp/#/ds/sc.root.sale.customers/edit/14 ```
Print Informations button, so I had to copy the file ``` Partner.rptdesign ``` , from my source code to the ```birt/report`` directory 
Birt Report Engine 4.4.2 ```http://www.eclipse.org/downloads/download.php?file=/birt/downloads/drops/R-R1-4_4_2-201502171805/birt-runtime-4_4_2-20150217.zip```

TODO: Play with the application.properties inside abs-webapp to relocate the reports. Secondly I wonder why axelor gradle build doesn't copy the reports from resource/reports, I had to copy it manually.

Hope this guide you to something, I am still playing around with Axelor adk.

![screen shot 2015-11-15 at 00 08 50](https://cloud.githubusercontent.com/assets/4633823/11167585/761dc85e-8b2d-11e5-857f-2fd547a78df8.png)

**Comment by gdu-axelor** [comment]
Now (master branch), the application can manage embedded and external Birt engine.

The objective is to simplify the application deployment.

A new parameter has been added in the applications.properties file (axelor.report.use.embedded.engine), to select the report engine. Default is to use embedded Birt engine.

With embedded Birt, there is nothing to do.

Regards
