### ISSUE TITLE
Cannot add contact when i installed crm module.

### ISSUE THREAD

**Issue by xgj1988** [axelor/abs-webapp#23]
When I add new contact  , I have a question ,I see the stacktrace , The error is about not base_sequence,  which code is partner. And the table has no record. I found the base_sequence.csv in axelor_base module.
The path is src/main/resources/data-init/aap/en/base_sequence.csv.but why it does't import when i initialize database!

**Comment by dougyfresh42** [comment]
I think the issue adding a new contact is discussed in [this forum post](https://forum.axelor.com/t/problem-adding-customer-to-crm/1687/12) over at the forums, but basically you need to add an address before you can add contacts.  It's a bug that should be fixed by next release.
