### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by skanel** [axelor/abs-webapp#5]
git clone git@github.com:axelor/abs-webapp.git
Cloning into 'abs-webapp'...
sign_and_send_pubkey: signing failed: agent refused operation
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by gdu-axelor** [comment]
You have to use https mode to clone the project : 

git clone https://github.com/axelor/abs-webapp.git
